server:
  port: 8080
###########################################################################
####### Data source setting
###########################################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sparrow
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl


